### ISSUE TITLE
Invited guild members cause error

### ISSUE THREAD

**Issue by synsless** [Perlkonig/avabur-clan-stats#2] opened 2018-05-10 19:25 UTC
It seems like users who have been invited to a guild but have not accepted cause  an issue.

---------------------------------

Traceback (most recent call last):
  File "collect.py", line 278, in <module>
    c.execute("REPLACE INTO members (userid, datestamp, username, level, fishing, woodcutting, mining, stonecutting, crafting, carving, stats, kills, deaths, harvests, resources, craftingacts, carvingacts, quests, totalacts, lastactive, d_crystals, d_platinum, d_gold, d_food, d_wood, d_iron, d_stone, d_xp) VALUES (?, date('now'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", (int(member['userid']), k, profiles[k]['level'], profiles[k]['fishing'], profiles[k]['woodcutting'], profiles[k]['mining'], profiles[k]['stonecutting'], profiles[k]['crafting'], profiles[k]['carving'], profiles[k]['stats'], profiles[k]['kills'], profiles[k]['deaths'], profiles[k]['harvests'], profiles[k]['resources'], profiles[k]['crafting_acts'], profiles[k]['carving_acts'], profiles[k]['quests'], totalacts, int(member['active_time']), donations[k]['crystals'], donations[k]['platinum'], donations[k]['gold'], donations[k]['food'], donations[k]['wood'], donations[k]['iron'], donations[k]['stone'], donations[k]['experiences']))
KeyError: 'vrath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "collect.py", line 313, in <module>
    raise RuntimeError("An error occured while storing fetched data: {}".format(repr(e)))
RuntimeError: An error occured while storing fetched data: KeyError('vrath',)

**Comment by Perlkonig** [comment] 2018-05-10 21:41
How odd. This was a problem with applicants. I assumed my solution would also apply to invitees. Are you using the latest version? I'll have to try to replicate so I can find out what the issue is.

**Comment by synsless** [comment] 2018-05-11 01:15
Yeah, I pulled it today before you made the latest update. I just added a check to get around it:

`if member['rankname'] == 'Invited':`

**Comment by Perlkonig** [comment] 2018-05-11 13:30
Can you submit a PR? Otherwise I'll tinker with this tonight when I get home.

**Comment by Perlkonig** [comment] 2018-07-29 18:31
PR merged.

**Closed as completed by Perlkonig** 2018-07-29 18:31 UTC
